export const PRODUCTS_DATA = [
    {
        id: 1,
        name: 'Sofa Bed',
        price: 299.99,
        description: 'A versatile sofa bed perfect for your living room or study, providingcomfort and functionality',
        image: './public/products/sofaBed.jpg',
    },
    {
        id: 2,
        name: 'Ceramic Vase',
        price: 49.99,
        description: 'A beautifully crafted ceramic vase to add an elegant touch to your decor',
        image: './public/products/ceramicVasa.jpg',
    },
    {
        id: 3,
        name: 'Clock',
        price: 19.99,
        description: 'A stylish clock to keep you on time and complement your study decor',
        image: './public/products/clock.jpg',
    },
    {
        id: 4,
        name: 'Coffee',
        price: 12.99,
        description: 'Premium quality coffee beans to start your day with a perfect brew',
        image: './public/products/coffee.jpg',
    },
    {
        id: 5,
        name: 'Lounge Chair',
        price: 199.99,
        description: 'A comfortable lounge chair ideal for relaxation in your living room or study',
        image: './public/products/loungechair.jpg',
    },
    {
        id: 6,
        name: 'Reclining Sofa',
        price: 399.99,
        description: 'A reclining sofa that combines comfort and style for your living space.',
        image: './public/products/recliningsofa.jpg',
    },
    {
        id: 7,
        name: 'Side Table',
        price: 89.99,
        description: 'A sleek side table to complement your living room or study decor.',
        image: './public/products/sideTable.jpg',
    },
    {
        id: 8,
        name: 'Study Desk',
        price: 159.99,
        description: 'A functional study desk designed to enhance productivity and style in your workspace.',
        image: './public/products/studyDesk.jpg',
    },
    {
        id: 9,
        name: 'Table Lamp',
        price: 29.99,
        description: 'An elegant table lamp to brighten up your study or bedside table.',
        image: './public/products/tableLamp.jpg',
    },
    {
        id: 10,
        name: 'Wooden Bookcase',
        price: 119.99,
        description: 'A sturdy wooden bookcase to organize and display your books and decor items.',
        image: './public/products/wodenBookcase.jpg',
    },
    {
        id: 11,
        name: 'Zen Dresser',
        price: 249.99,
        description: 'A zen-inspired dresser to keep your space organized and serene.',
        image: './public/products/zenDresser.jpg',
    },
];
